In [1]:
#!pip install mysql-connector-python

In [2]:
import mysql.connector # inside the my sql we have connect method given below.

In [3]:
# Conect to server 
cnx = mysql.connector.connect(
    host = "127.0.0.1",# this 127.0.0.1 is the local ip adress of our computer.
    port = 3306,
    user = "root",
    password= "3636")
#this above all about  connect to server command call it in panda command given below.

In [4]:
import pandas as pd
con = mysql.connector.connect(
    host = "localhost",    # this 127.0.0.1 is also written as "localhost" here..
    port = 3306,
    user = "root",
    password = "3636",  # Note :- always care about coma because coma gives error.    
    database ="studentdb" )

#https://pandas.pydata.org/panda.docs/version/0.23.4/generated/pandas.read_sql_query.html

df=pd.read_sql_query("select * from department", con) # con is connection and this connection is provide details into system at my sql server(host,server,user,password etc) 
df
df.head(5) #df=data frame #head method showing top (5) rows here.

did          dname
0  1001          sales
1  1002      marketing
2  1003  manufacturing
3  1004             HR
4  1005        finance

In [5]:
df.tail(3) #tail method is going to show last (3) rows.

did          dname
2  1003  manufacturing
3  1004             HR
4  1005        finance

In [6]:
df=pd.read_sql_query("select * from department", con) # con is connection and this connection is provide details into system at my sql server(host,server,user,password etc) 
df

did          dname
0  1001          sales
1  1002      marketing
2  1003  manufacturing
3  1004             HR
4  1005        finance

In [7]:
df.sample() #sample gives any row data form table randomly.

did    dname
4  1005  finance

In [8]:
df.sample(3) # this sample gives any 3 row data form table randomly. 

did          dname
2  1003  manufacturing
1  1002      marketing
3  1004             HR

In [9]:
df=pd.read_sql_query("select * from department where did = '1001' ", con)
df

did  dname
0  1001  sales

In [10]:
res=pd.read_sql_query("select * from department where dname like  'An%' ", con)
res

Empty DataFrame
Columns: [did, dname]
Index: []

In [11]:
df=pd.read_sql_query("select * from department where did = 1003", con)
df
# by this method we can give any query like 1, where 1, any run query etc but don't give any update query and delete query that need saperate query only select query u can use here.

did          dname
0  1003  manufacturing

In [12]:
def sqlfunc(sql):
    res = pd.read_sql_query(sql,con)
    return (res)                       

In [13]:
res =sqlfunc("select * from department")
res

did          dname
0  1001          sales
1  1002      marketing
2  1003  manufacturing
3  1004             HR
4  1005        finance

In [14]:
res =sqlfunc("select * from employee")
res

empid   ename      emailid   did
0      1    jhon   jh@abc.com  1001
1      2  henery   hn@abc.com  1001
2      3    josh   js@abc.com  1001
3      4   josh2  js2@abc.com  1002
4      5    eric  er2@abc.com  1002
5      6  grande  grn@abc.com  1003

In [17]:
res = sqlfunc("select * from employee where dname like 'M%'")
res

DatabaseError: Execution failed on sql 'select * from employee where dname like 'M%'': 1054 (42S22): Unknown column 'dname' in 'where clause'

In [18]:
res.columns

Index(['empid', 'ename', 'emailid', 'did'], dtype='object')

In [19]:
res=sqlfunc('select count(did) from studentdb')
res

DatabaseError: Execution failed on sql 'select count(did) from studentdb': 1146 (42S02): Table 'studentdb.studentdb' doesn't exist

In [ ]:
res =sqlfunc("select * didtinct(did) from studentdb")
res

### my sql fundalmental is complete here .

# Numpy Tutorial : -

#### NumPy is a python pacakage . it stand for "Numieriacal Python".It is a library consisting of dimensional array object and a collection of routine for processing of array.

* Numpy, which stands, for Numerical Python, is a library consisting of multidimensinol array objects and a collection of routines for processing those arrays.

* Using NumPy , mathmetical and logical operations on arrays can be performed.

#### Operations using NumPy :-

* Using NumPy, a developer can perform the following operations :-

    ** Mathmatical and logical operations.

    ** Fourier transforms and routines for shape manipulation.

    ** NumPy has in-built functions for linear algebra and random number generation.

Go to notes reposatery from here :-->
https://drive.google.com/file/d/1Qdgc45X3_60yokZ3AevY6OwbC8-RVzC0/view

In [20]:
import numpy

In [21]:
x=numpy.array([1,2,3])

In [22]:
x

array([1, 2, 3])

In [23]:
a=numpy.array([1,2,3,4,5])

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
a.shape #  Shape is the meant for total number of elements.

(5,)

In [26]:
b=numpy.array([11,22,33,44,55])

In [27]:
b

array([11, 22, 33, 44, 55])

In [28]:
b.shape

(5,)

In [29]:
import numpy as np # to make any shortest name we use this method example 'numpy'---->'np'.

In [30]:
a=np.array([1,2,3,4,5])

In [31]:
a

array([1, 2, 3, 4, 5])

In [32]:
a.shape

(5,)

##### Note:- whenever we are working with list we can work with single dimenction only but ahead  with numpy we can work multidimensional Data.

In [33]:
a=np.array([45,24,33,42,555])
a

array([ 45,  24,  33,  42, 555])

In [34]:
a=np.array([12,121,13,14,15])
a

array([ 12, 121,  13,  14,  15])

In [35]:
a.shape

(5,)

In [36]:
a=np.array([42,32,333,46,15,16])
a

array([ 42,  32, 333,  46,  15,  16])

In [37]:
a.shape

(6,)

In [38]:
# One dimentional array creation
a1=np.array([56,78,34,22])
a1

array([56, 78, 34, 22])

In [39]:
a1.shape

(4,)

In [40]:
#Two dimensional array ceration it will represent the data in rows columns format.

a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [41]:
a.shape #in output (2,2) means 2 rows and 2 columns  present in data.

(2, 2)

##### Note - Shape is giving  us rows and columns.

In [42]:
#Note :- Again two dimensional here, two dimensional means "ROWS*COLOUMNS".
c=np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
c.shape # in output (3,2) means 3 rows and 2 columns present in data.

(3, 2)

In [44]:
x=np.array([[61,21,89],[32,42,56]]) 
x

array([[61, 21, 89],
       [32, 42, 56]])

In [45]:
x.shape   #2 rows aand 3 columns.

(2, 3)

In [46]:
b=np.array([[11,22,33],[44,55,66]])
b

array([[11, 22, 33],
       [44, 55, 66]])

In [47]:
b.shape   #2 rows aand 3 columns.

(2, 3)

In [48]:
d=np.array([[11,22,33],[44,55,66],[77,88,99]])
d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [49]:
d.shape

(3, 3)

In [50]:
e=np.array([[11,22,33,0],[44,55,66,1],[77,88,99,2]])
e

array([[11, 22, 33,  0],
       [44, 55, 66,  1],
       [77, 88, 99,  2]])

In [51]:
e.shape

(3, 4)

In [52]:
f=np.array([[11,22,33],[44,55,66]])
f

array([[11, 22, 33],
       [44, 55, 66]])

In [53]:
f.shape

(2, 3)

In [54]:
g=np.array([[11,22],[44,55],[77,88]])
g

array([[11, 22],
       [44, 55],
       [77, 88]])

In [55]:
g.shape

(3, 2)

In [56]:
h=np.array([[11,22,33],[44,55,66],[77,88,99],[1,2,3]])
h

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99],
       [ 1,  2,  3]])

In [57]:
h.shape

(4, 3)

In [58]:
i=np.array([[11,22,33,0],[44,55,66,1],[77,88,99,2],[1,2,3,4]])
i

array([[11, 22, 33,  0],
       [44, 55, 66,  1],
       [77, 88, 99,  2],
       [ 1,  2,  3,  4]])

In [59]:
i.shape

(4, 4)

THE SESSION END