In [1]:
import numpy as np #write this statement before the write new statement as below.

In [2]:
a=np.array([[4,5,6,],[6,7,8],[3,7,9]])

In [3]:
a

array([[4, 5, 6],
       [6, 7, 8],
       [3, 7, 9]])

In [4]:
#it gives shape in dimension :- Rows and Coloumns
a.shape

(3, 3)

In [5]:
#this .size method gives total no of elements in dimension.
a.size

9

In [6]:
#this .itemsize attributes gives the number of bites/memory occupied by each element.
a.itemsize

4

In [7]:
# this .dtype method use to know data type.
a.dtype

dtype('int32')

* int32 and int64 these arethe general datatypes in python.

* int32 :- this one consider when range is very less. whenever we want store the positive data  upto 0 to 65k arround.

* int64 :- This one consider when the range of data exceed more than int32 then it will automatically consider itd range is very high it can store data range in billons. it will take store data 8 byte. 


In [8]:
#this .min() method gives the min value in all of the elements in dimension.
a.min()

3

In [9]:
#this .mmax() method gives the max value in all of the elements in dimension.
a.max()

9

In [10]:
#this .data method gives the memory adress
a.data

In [11]:
#To change datatype or assingned the dataype in decimal there is a arguement in np.array(       ,dtype='float64').
# and the value those are in integer value the output will come in decimal value.
#Because we change data type in float.float64 means devided by 8 this mean 64/8=8 byte.
#so generally float occupied 8 byte to store the data. 


a=np.array([[1,2],[3,4],[5,6]],dtype='float64')
#c1=np.array([[1,2][3,4],[5,6]])

a
#c1

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [12]:
# this gives number of bytes : It is float data type hence it takes 8 byte to store the data.
a.itemsize

8

In [13]:
a.shape

(3, 2)

In [14]:
#By changing the the shape (rows and coloumns) value we can reshape it by .rshape value.

a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
# Inside the numpy arrange function in there. Inside the arrange function whenever puting any of the value (int value) we can generate the sequence of the integer.
#This is similar to range function in python class.

x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [17]:
#after arange/generating the we can give reshape the data into numpy arrayy (rows and coloumns).

a=x.reshape(3,5) 

#Ex:- given below

In [18]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
a=x.reshape(5,3)

In [20]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
x=np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
x.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
a=np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [24]:
a.shape

(5, 7)

In [25]:
#There is .ndim(n dimension) atribute inside the numpy. 
#n-dimension stand for how many no of dimensions means  two dimensional here with means rows and columns are two dimensional. 
#Means x and y in plot.

a.ndim

2

In [26]:
a.dtype  # to know data type and dtype('int32') takes 4 byte each element to store the data. 

dtype('int32')

In [27]:
a.itemsize

# int32 divided into 32/8 =4 it means it takes 4 byte each element to store the data.

4

In [28]:
a.size

#it showing  size of the data means total number of elements.

35

In [29]:
type(a) # It is showing the 'numpy ndarray' means multidimensional array.   

numpy.ndarray

In [30]:
b=np.array([6,7,8])

In [31]:
b

array([6, 7, 8])

In [32]:
type(b)

numpy.ndarray

In [33]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='float32')

In [34]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [35]:
ra=np.array([[34,78,89],[22,33,77]])
ra

array([[34, 78, 89],
       [22, 33, 77]])

In [36]:
# Ravel operation where we can convert  one numpy array (rows and coulms) into asingle row i.e. ravel.

print(ra.ravel())

[34 78 89 22 33 77]


In [37]:
b=np.array([(1.5,2,3),(4,5,6)],dtype = 'int32') #By this method we can change float data type into integer.

b

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.zeros((3,4)) #this function create data automatically rows and coloums with zeros and by default it is float.  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((3,4)) #this function create data automatically rows and coloums with ones. and by default it is float.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# Inside the numpy three dimensional like as x,y,z thats why numpy known as multidimensional array data.

# example of 3dimensional :-dekhne ke lie tick:-  2 set ,dono me 3 rows,dono me 4 coloumns to ho gya 3 dimensional.

j=np.ones((2,3,4))
j

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
j.shape

(2, 3, 4)

In [42]:
j.ndim

3

In [43]:
np.ones((2,3,4),dtype=np.int32) #We can make it datatype decimal to integer type data by this method.

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [44]:
np.empty((5,5))

# Inside the numpy there is a function to generate empty data , Empty data means junk value so it can take any junk value(randamly) from ifinite value. 

array([[4.67296746e-307, 1.69121096e-306, 1.86921822e-306,
        1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 8.90104239e-307,
        6.89804132e-307, 9.34605716e-307],
       [1.37962456e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307],
       [8.90111708e-307, 3.22643519e-307, 9.79103798e-307,
        2.46155235e-312, 2.18568966e-312]])

In [45]:
# (St art,End,Skip or Jump) here in arange function  in numpy similar to range function range(starting value,ending value ,skip value) we were study.


np.arange(10,70,6)

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [46]:
np.arange(10,70,6)

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [47]:
import numpy as np
np.linspace(0,5,10)

#Inside the numpy linespace(line spaces) functionis there and line space function generate the rular line hre line starting from 0 and ending upto 5 and generate 10gap between 0 to 5.  

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [48]:
a=np.arange(6)

In [49]:
a

array([0, 1, 2, 3, 4, 5])

In [50]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [52]:
#subtraction in numpy
c=a-b
print(c)

[20 29 38 47]


In [53]:
#squaring in numpy
b**2

array([0, 1, 4, 9], dtype=int32)

In [54]:
#inside the numpy there is random package and inside it there is a random function.
#This random function generate the any data value randomly.
#Random function not similar to the empty function because empty function generate junk value(fake value) so we cant use for adding or substracting etc purpose
#But random function generate random value(real time value) so we can use it for adding or substracting etc purpose.

b=np.random.random((2,3))

In [55]:
b

array([[0.35283349, 0.39720975, 0.16982532],
       [0.07711989, 0.87556945, 0.18569521]])

In [56]:
c=np.ones((2,3))

In [57]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
d=b+c
d

array([[1.35283349, 1.39720975, 1.16982532],
       [1.07711989, 1.87556945, 1.18569521]])

# Universal Functions :-

* Universal Functions :- Numpy provides various universal functions that cover a wide variety of operations. These functions include standard trigonometric functions, functions for arithmetic operations, handling complex numbers, statistical functions, etc. 

In [59]:
B=np.arange(3)

In [60]:
B

array([0, 1, 2])

In [61]:
#exponential function.
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [62]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [63]:
c=np.array((2,1,4))
np.add(B,c)

array([2, 2, 6])

# Indexing, Sliceing, and Itrating :-

In [64]:
a=np.arange(10)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#calling data by indexing value

a[2]

2

In [67]:
#Slicing between 2 to 5 so output is 2,3,4 and 
# ***--> 5 is exclusive here this will be not including in the result. 

a[2:5]

array([2, 3, 4])

In [68]:
#negative Indexing 
a[-1]

9

In [69]:
a[-2]

8

In [70]:
a[-3]

7

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# Negative indexing -4 to end value.
a[-4:]

array([6, 7, 8, 9])

In [73]:
a[-4:-2]

array([6, 7])

Basic  sliceing is an extension of python's basic concept of slicing to n diamentions.Apython slice oblect is constructed by giving start,atop and step parameters to the built-in slice function. this slice object is passed to the array to extract a part of array.

In [74]:
import numpy as np
d1 = np.arange (20) #It will generate 20 data we know that.

In [75]:
#An ndarray object is prepared by arange () function.
#Then a slice object is defined with start, stop and step value 2,20, and 2 respectively.
#and there is inbuilt slice function in the python. 

s = slice(2,20,2) 

In [76]:
print (d1[s]) #checking d1 data and it will deliver the data with [s] hre s is slice operation given 2 to 20 with jumping with 2.

[ 2  4  6  8 10 12 14 16 18]


In [77]:
d2 = np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
d2[5:] #slicing from 5th index till end of the array.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [79]:
#Sometime we have missing data missing data means we don't know data type wether it is str,float,int etc.
#missing means it could be anything but i can't put zero.
#Where is missing data in numpy we fill it with by "np.nan".means data is missing from here.


d3 = np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [80]:
#   ~ this symbolconsidering as NOT which means it is not nan.it will showing only present data.

print(d3[~np.isnan(d3)])

[1. 2. 3. 6. 7. 8.]


The random module provides nice functions to generate random numbers (and also statistical ditributions) of any shape.rand function will gererate any number between 0 and 1 .

In [81]:
#Inside the numpy random funtion is there and inside the random rand function is present.
#Rand function will gererate any value between 0 and 1 .


np.random.rand(2,2)    #uniform distribution  ----> similar like format

array([[0.2026229 , 0.99822099],
       [0.63770406, 0.68214118]])

Randn will generate any number for normal distribution in given dimension format.


In [82]:
#Inside the numpy random funtion is there and inside the random randn function is present.
#Randn function will gererate any value between -1 and 1 .
#Random function is generally to get statistical Data.

np.random.randn(2,3)

array([[-1.0508122 , -1.06596433,  1.38647579],
       [-0.45969584, -0.79438413, -0.30024028]])

In [83]:
# Done With basic numpy(numerical python).
# It works with only number data so it is numpy(numerical python) 

# PANDAS :-

Pandas is very important library and pandas is buit on to the numpy basically. 

* Inside pandas we can create table like structure which have rows and columns.

#### Introduction to Pandas :-
* Library for computation with tabular data.
* Mixed typed of data(int,str,float,char.) allowed in single table.
* Columns and rows of data can be 
* Advanced data aggreation and statical functions.

There are lable axis which means  rows is lable with index value and  columns is lable with (name, id salary etc).

There are axis which is indicating :-
    
    axis=0 :- it means we are talking about rows.
    
    axis=1 :- it means we are talking about columns.

Go to notes repository from page no 19 :-
    https://drive.google.com/file/d/1Qdgc45X3_60yokZ3AevY6OwbC8-RVzC0/view

Inside the Panda two data structure :-
    
    Series :- It is use for the one dimensional structure.
        
    Dataframe :-It is use for the two dimensional data means rows and coloums or tabular structure 

In [84]:
import pandas as pd # pd stand for pandas.
import numpy as np # np stand for numpy.

In [85]:
a=pd.Series([1,2,3,4]) #inside pandas int64 means 8 byte per element consuming.
a

0    1
1    2
2    3
3    4
dtype: int64

In [86]:
b=pd.Series([11,22,33,44,55]) # *** Here in Series S is capital letter.
b  


#Series data structure gives one vector means one dimentional.
#And there is a index value means index value must be unique and
#it is enternally automatically generating  Default np.arrange(n), if no index is passing.

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [87]:
a=pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [88]:
b=pd.Series([11,22,33,44,55])
b

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [89]:
#By this method we can change the index value.


a=pd.Series([11,12,13,14,],index=[100,101,102,103])
a

100    11
101    12
102    13
103    14
dtype: int64

In [90]:
a=pd.Series([1,2,3,4],index=[91,92,93,94])
a

91    1
92    2
93    3
94    4
dtype: int64

In [91]:
z=pd.Series([1,2,3,4,5,6,7,8])
z

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [92]:
y=pd.Series([1,2,3,4,5,6],index=[100,101,102,103,104,105])
y

100    1
101    2
102    3
103    4
104    5
105    6
dtype: int64

In [93]:
#by default we have int64 data type in pandas but we can change data type with this method.
x=pd.Series([1,2,3],index=[10,11,12],dtype =float)
x

10    1.0
11    2.0
12    3.0
dtype: float64

In [94]:
#Series (data,index,dtype)

s=pd.Series([1,2,3,4,5],index=[11,12,13,14,15],dtype=float)

In [95]:
s

11    1.0
12    2.0
13    3.0
14    4.0
15    5.0
dtype: float64

In [96]:
#by default we have int64 data type in pandas but we can change data type with this method.

y=pd.Series([1,2,3,4,5,6],index=[10,11,12,13,14,15],dtype=float)
y

10    1.0
11    2.0
12    3.0
13    4.0
14    5.0
15    6.0
dtype: float64

In [97]:
#accessing the data from series by giving the index value :-

s=pd.Series ([20,34,39,42,59])

print(s[0]) #puting index value 

20


In [98]:
s[3] #index value

42

In [99]:
#retrive first three elements

s=pd.Series([10,20,30,40,50,60,70,80])
print(s[0:3])

0    10
1    20
2    30
dtype: int64


In [100]:
#passing data from list 
#here we are generating data with the help of numpy and pass it to pandas Series.
data = np.array([1,2,3,4])
m=pd.Series(data)
m

0    1
1    2
2    3
3    4
dtype: int32

In [101]:
#we can also pass the ditionary data to the pandas:-
demodict={'Name':'X','Age':12 }
s1 = pd.Series(demodict)

In [102]:
s1

Name     X
Age     12
dtype: object

In [103]:
#Task  create one dictionary object with cricketer name and run and pass it to pandas series print.

In [104]:
ckr = {'name':'virat','runs':243,'innings':3,'balls':56 }
ckr

{'name': 'virat', 'runs': 243, 'innings': 3, 'balls': 56}

In [105]:
#this ckr passing to the pd.seriesby this method

s2=pd.Series(ckr) #s2 to is variable name.

In [106]:
s2

name       virat
runs         243
innings        3
balls         56
dtype: object

DataFrame is a two dimensional data structure ,i.e. data is aligned in a tabular fashion in rows and columns.

Features of coloumns are of different types.

Size -Mutable

Labeked axis (rows and columns)

can perform arithmetic operation on rows and columns 

The End Session